print('You are a genius, continue with the hard work it will soon come to pay back')
print(233+232)
print("Hello, from double quotes")
print('232'+'2324')
print(199, 822)
print('John', 'Musa', 'Mike', 'Mudok')
print('Age', 100,  'City', 'Nairobi', 'Population', 4, 'Million')
