results = [{"name": "Emmanuel Keller", "maths": 42, "engllsh": 22, "chemistry": 76, "kiswahili": 71, "french": 22},
           {"name": "Wyoming Clarke", "maths": 63, "engllsh": 77, "chemistry": 49, "kiswahili": 38, "french": 17},
           {"name": "Adam Buckley", "maths": 49, "engllsh": 60, "chemistry": 52, "kiswahili": 50, "french": 63},
           {"name": "Flavia Mendoza", "maths": 70, "engllsh": 80, "chemistry": 65, "kiswahili": 56, "french": 22},
           {"name": "Cullen Roman", "maths": 83, "engllsh": 38, "chemistry": 42, "kiswahili": 55, "french": 33},
           {"name": "Kylie Myers", "maths": 68, "engllsh": 45, "chemistry": 82, "kiswahili": 35, "french": 75},
           {"name": "Kylynn Ford", "maths": 50, "engllsh": 58, "chemistry": 44, "kiswahili": 47, "french": 28},
           {"name": "Hope Johnson", "maths": 38, "engllsh": 78, "chemistry": 75, "kiswahili": 70, "french": 74},
           {"name": "Gretchen Waller", "maths": 32, "engllsh": 33, "chemistry": 40, "kiswahili": 37, "french": 57},
           {"name": "Alvin Harvey", "maths": 73, "engllsh": 66, "chemistry": 43, "kiswahili": 49, "french": 37},
           {"name": "Rudyard Love", "maths": 79, "engllsh": 20, "chemistry": 62, "kiswahili": 64, "french": 44},
           {"name": "Margaret Rocha", "maths": 88, "engllsh": 53, "chemistry": 59, "kiswahili": 74, "french": 23},
           {"name": "Cally Holcomb", "maths": 61, "engllsh": 71, "chemistry": 48, "kiswahili": 51, "french": 17},
           {"name": "Veronica Barr", "maths": 45, "engllsh": 78, "chemistry": 62, "kiswahili": 74, "french": 27},
           {"name": "Tad Avila", "maths": 53, "engllsh": 36, "chemistry": 83, "kiswahili": 54, "french": 40},
           {"name": "Dean Pope", "maths": 85, "engllsh": 65, "chemistry": 69, "kiswahili": 56, "french": 20},
           {"name": "Dorian Diaz", "maths": 80, "engllsh": 68, "chemistry": 73, "kiswahili": 43, "french": 28},
           {"name": "Fletcher Stanley", "maths": 82, "engllsh": 85, "chemistry": 79, "kiswahili": 56, "french": 76},
           {"name": "Abbot Donovan", "maths": 44, "engllsh": 84, "chemistry": 89, "kiswahili": 68, "french": 34},
           {"name": "Renee Nixon", "maths": 37, "engllsh": 34, "chemistry": 60, "kiswahili": 41, "french": 68},
           {"name": "Hyatt Yates", "maths": 54, "engllsh": 43, "chemistry": 67, "kiswahili": 75, "french": 32},
           {"name": "Aidan Francis", "maths": 66, "engllsh": 21, "chemistry": 59, "kiswahili": 36, "french": 71},
           {"name": "Sylvia Howe", "maths": 62, "engllsh": 25, "chemistry": 59, "kiswahili": 72, "french": 25},
           {"name": "Jael Horne", "maths": 65, "engllsh": 80, "chemistry": 70, "kiswahili": 41, "french": 74},
           {"name": "Kevin Walter", "maths": 64, "engllsh": 61, "chemistry": 44, "kiswahili": 49, "french": 79},
           {"name": "Ferdinand Mason", "maths": 89, "engllsh": 34, "chemistry": 67, "kiswahili": 77, "french": 36},
           {"name": "Hakeem Harrison", "maths": 80, "engllsh": 48, "chemistry": 89, "kiswahili": 67, "french": 31},
           {"name": "Kennan Foster", "maths": 67, "engllsh": 66, "chemistry": 43, "kiswahili": 49, "french": 68},
           {"name": "Steven Lee", "maths": 57, "engllsh": 84, "chemistry": 91, "kiswahili": 73, "french": 67},
           {"name": "Phoebe Miller", "maths": 32, "engllsh": 74, "chemistry": 90, "kiswahili": 41, "french": 57},
           {"name": "Halee Branch", "maths": 86, "engllsh": 30, "chemistry": 63, "kiswahili": 74, "french": 48},
           {"name": "Britanni Barker", "maths": 46, "engllsh": 23, "chemistry": 57, "kiswahili": 74, "french": 69},
           {"name": "Kai Fischer", "maths": 72, "engllsh": 67, "chemistry": 60, "kiswahili": 75, "french": 71},
           {"name": "Travis Tyler", "maths": 65, "engllsh": 43, "chemistry": 41, "kiswahili": 75, "french": 18},
           {"name": "Arthur Singleton", "maths": 82, "engllsh": 40, "chemistry": 54, "kiswahili": 60, "french": 77},
           {"name": "Ferris Gill", "maths": 88, "engllsh": 39, "chemistry": 57, "kiswahili": 57, "french": 49},
           {"name": "Colby Rhodes", "maths": 50, "engllsh": 22, "chemistry": 89, "kiswahili": 62, "french": 47},
           {"name": "Jolie Hubbard", "maths": 30, "engllsh": 28, "chemistry": 77, "kiswahili": 78, "french": 70},
           {"name": "Tatum Ellison", "maths": 75, "engllsh": 23, "chemistry": 66, "kiswahili": 46, "french": 64},
           {"name": "Myles Mcmahon", "maths": 86, "engllsh": 82, "chemistry": 52, "kiswahili": 55, "french": 76},
           {"name": "Willow Oneal", "maths": 44, "engllsh": 46, "chemistry": 86, "kiswahili": 45, "french": 18},
           {"name": "Ferris Campbell", "maths": 90, "engllsh": 43, "chemistry": 79, "kiswahili": 62, "french": 28},
           {"name": "Harding Harris", "maths": 37, "engllsh": 29, "chemistry": 67, "kiswahili": 52, "french": 68},
           {"name": "Ori Flynn", "maths": 86, "engllsh": 75, "chemistry": 70, "kiswahili": 73, "french": 61},
           {"name": "Derek Colon", "maths": 86, "engllsh": 84, "chemistry": 81, "kiswahili": 41, "french": 32},
           {"name": "Willow Long", "maths": 54, "engllsh": 65, "chemistry": 71, "kiswahili": 68, "french": 62},
           {"name": "Trevor Leonard", "maths": 65, "engllsh": 49, "chemistry": 46, "kiswahili": 51, "french": 18},
           {"name": "Cheryl Salazar", "maths": 52, "engllsh": 49, "chemistry": 91, "kiswahili": 52, "french": 28},
           {"name": "Ayanna Moreno", "maths": 58, "engllsh": 42, "chemistry": 67, "kiswahili": 69, "french": 25},
           {"name": "Leilani Herrera", "maths": 49, "engllsh": 61, "chemistry": 89, "kiswahili": 59, "french": 40}]

student = results[0]
print(student)
print(type(student))

# for s in results:
#     print(s["name"])
#     print(s["maths"])
#     print(s["english"])
